name: Demo Workflow

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Src
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Verbose
        run: cargo build --verbose

      - name: Test Verbose
        run: cargo test --verbose
